In [1]:
import numpy as np
## create arrays using numpy

In [ ]:
# 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [8]:
arr2 = np.array([1,2,3,4,5])


arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [ ]:
#2D array 
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)


[[1 2 3 4 5]
 [2 3 4 5 6]]


In [18]:
print(np.arange(0,10,2).reshape(5,1))

[[0]
 [2]
 [4]
 [6]
 [8]]


In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
arr = np.array([[1,2,3],[4,5,6]])
print("Array: \n",arr)
print("Shape:\n",arr.shape)
print("No.of Dimensions:",arr.ndim)
print(arr.dtype)

Array: 
 [[1 2 3]
 [4 5 6]]
Shape:
 (2, 3)
No.of Dimensions: 2
int64


In [27]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]


In [28]:
#Universal functions
arr = np.array([2,3,4,5,6])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [30]:
#array slicing and indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
print(arr[1][3])

8


In [39]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [40]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [41]:
arr[0][0] = 100
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [43]:
arr[1:] = 100
arr

array([[100,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [44]:
#normalization : mean = 0 , S.D = 1 
data = np.array([1,2,3,4,5])
mean = np.mean(data)
std_dev = np.std(data)
#normalized data
nrml_data = (data-mean) / std_dev
print(f"Normalized data : {nrml_data}")

Normalized data : [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [45]:
variance = np.var(data)
print(f"Variance {variance} ")

Variance 2.0 


In [54]:
#logicaal operation
data = np.array([1,2,3,4,5,6,7,8,9,10])
print(data > 5)
print(data[data > 5])
print(data[(data>=5) & (data<=8)])

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[5 6 7 8]
